FROM osrf/ros:noetic-desktop-full

# Install system dependencies.
RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Copy the source code into the container.
WORKDIR /ros_gazebo_gym_ws
COPY . /ros_gazebo_gym_ws/src

# Install ROS dependencies.
RUN apt-get update && \
    rosdep update && \
    rosdep install --reinstall --from-path src --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*
