#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# ros_gazebo_gym documentation build configuration file, created by
# sphinx-quickstart on Tue Jul 10 17:48:23 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
import sys
from datetime import datetime
from pathlib import Path

import catkin_pkg.package

# -- Make sure ros-gazebo-gym is accessible without going through setup.py -----------
catkin_dir = Path(__file__).joinpath("../../..").resolve()
catkin_package = catkin_pkg.package.parse_package(
    catkin_dir.joinpath(catkin_pkg.package.PACKAGE_MANIFEST_FILENAME)
)
sys.path.insert(0, str(catkin_dir))
sys.path.insert(1, str(catkin_dir.joinpath("templates")))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "3.0"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.imgmath",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "myst_parser",
]

# Extension settings
autosummary_generate = True
autosummary_generate_overwrite = True
autodoc_member_order = "bysource"

# imgmath settings
imgmath_image_format = "svg"
imgmath_font_size = 14

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# Map suffix(es) to parsers
source_suffix = {".rst": "restructuredtext", ".txt": "markdown", ".md": "markdown"}

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "ros-gazebo-gym"
copyright = f"{datetime.now().year}, Rick Staa"
author = "Rick Staa"
git_user_name = "rickstaa"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = catkin_package.version
# The full version, including alpha/beta/rc tags.
release = catkin_package.version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "TODO.*", "README.*"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "default"  # 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_logo = "images/logo.svg"
html_favicon = "_static/favicon.ico"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {"logo_only": True}
html_context = {
    "display_github": True,  # Add 'Edit on Github' link instead of 'View page source'
    "github_user": git_user_name,
    "github_repo": project,
    "github_version": "main",
    "conf_py_path": "/docs/source/",  # needs leading and trailing slashes!
}

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "ROSGazeboGymdoc"

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "ros_gazebo_gym.tex",
        "ROS Gazebo Gym Documentation",
        "Rick Staa",
        "manual",
    ),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "ros_gazebo_gym", "ROS Gazebo Gym Documentation", [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "ros_gazebo_gym",
        "ros_gazebo_gym Documentation",
        author,
        "ros_gazebo_gym",
        "Framework that allows you to train RL algorithms on Gazebo environments.",
        "Miscellaneous",
    ),
]

# -- External links dictionary -----------------------------------------------
# Here you will find some often used global url definitions and intersphinx mappings.
intersphinx_mapping = {"https://docs.python.org/": None}

extlinks = {
    "panda_gazebo": (
        "https://github.com/rickstaa/panda-gazebo/tree/noetic-devel/%s",
        None,
    ),
    "ros_gazebo_gym": (
        "https://github.com/rickstaa/ros-gazebo-gym/tree/noetic/%s",
        None,
    ),
}


# -- Add extra style sheets --------------------------------------------------
def setup(app):
    app.add_css_file("css/modify.css")
